apiVersion: v1
kind: Service
metadata:
  name: nginx-node-port
  namespace: test
  labels:
    app: test
    env: test
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30080 # optional, but useful for testing
  selector:
    app: nginx-minimal
