apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: external-secrets

namespace: es

resources:
  - ./css.yaml

helmCharts:
  - name: external-secrets
    repo: https://charts.external-secrets.io
    releaseName: external-secrets
    version: 0.18.2
    namespace: es
    includeCRDs: true
