apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mesapi
  name: mes-api-deployment
  labels:
    app: mes-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mes-api
  template:
    metadata:
      labels:
        app: mes-api
    spec:
      containers:
      - name: mes-api
        imagePullPolicy: Always
        image: ghcr.io/mervinhemaraju/mauritius-emergency-service-api:dev
        env:
        - name: UWSGI_PROTOCOL
          value: "http"
        ports:
        - containerPort: 8081
        
        # Health checks
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3

        # Resource limits
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"