apiVersion: v1
kind: Pod
metadata:
  name: nginx-minimal
  namespace: test
  labels:
    app: test
    env: test
spec:
  containers:
    - name: nginx
      image: nginx:1.23.3
      ports:
        - containerPort: 80
          protocol: TCP
      readinessProbe:
        httpGet:
          path: /
          port: 80
      resources:
        limits:
          cpu: 250m
          memory: 50Mi
        requests:
          cpu: 250m
          memory: 50Mi
      # volumeMounts:
      #   - name: test-volume
      #     mountPath: /usr/share/nginx/html
