apiVersion: v1
kind: Service
metadata:
  name: nginx-cluster-ip
  namespace: test
  labels:
    app: test
    env: test
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: nginx-minimal
