apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-token
  namespace: ed
spec:
  # Reference to the ClusterSecretStore
  secretStoreRef:
    name: doppler-apps-creds
    kind: ClusterSecretStore

  # Describes the Kubernetes Secret that will be created
  target:
    name: cloudflare-creds      # Name of the Kubernetes Secret to be created
    creationPolicy: Owner       # The secret will be deleted when this ExternalSecret is deleted

  # Describes the data to fetch from Doppler
  data:
  - secretKey: CLOUDFLARE_TERRAFORM_TOKEN
    remoteRef:
      key: CLOUDFLARE_TERRAFORM_TOKEN