provider:
  name: cloudflare
env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cf-creds
        key: dnsapitoken

logLevel: info
policy: sync
registry: txt
txtOwnerId: external-dns-mervinhemaraju-com

sources:
  - service  
  - ingress
  - traefik-proxy
extraArgs:
  - --cloudflare-proxied
  - --cloudflare-record-comment="provisioned by external-dns"
  - --traefik-disable-legacy
  - --ignore-ingress-rules-spec
  - --ignore-ingress-tls-spec

domainFilters:
  - mervinhemaraju.com

triggerLoopOnEvent: true
interval: 1m

serviceMonitor:
  enabled: false