provider:
  name: cloudflare

env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cf-creds
        key: dnsapitoken

logLevel: info
policy: sync
registry: txt
txtOwnerId: external-dns-plagueworks-org

sources:
  - service  
  - ingress
  - traefik-proxy
extraArgs:
  - --cloudflare-proxied
  - --traefik-disable-legacy
  - --ignore-ingress-rules-spec
  - --ignore-ingress-tls-spec

domainFilters:
  - plagueworks.org

triggerLoopOnEvent: true
interval: 1m

serviceMonitor:
  enabled: false