apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik

resources:
- namespace.yaml
# - rbac.yaml

helmCharts:
- name: traefik
  repo: https://helm.traefik.io/traefik
  version: 23.1.0
  releaseName: traefik
  includeCRDs: true
  valuesFile: values.yaml
