apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: traefik

namespace: traefik

resources:
  - ./es.yaml

helmCharts:
  - name: traefik
    repo: https://traefik.github.io/charts
    releaseName: traefik
    version: 35.4.0
    namespace: traefik
    includeCRDs: true
    additionalValuesFiles:
      - values.yaml