---
##### HTTP to HTTPS redirects ##########
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
spec:
  redirectScheme:
    scheme: https
    permanent: true

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: custom-headers-request
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https" # Adds


# ---
# ##### HTTP to HTTPS redirects ##########
# apiVersion: traefik.io/v1alpha1
# kind: Middleware
# metadata:
#   name: security-headers
# spec:
#   headers:
#     customFrameOptionsValue: sameorigin
#     browserXssFilter: true
#     frameDeny: true
#   #  contentSecurityPolicy: "frame-ancestors 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval';"
#     referrerPolicy: strict-origin
#     customResponseHeaders:
#       Permissions-Policy: "geolocation=(self), microphone=(), camera=(), fullscreen=*"
