---
##### HTTP to HTTPS redirects ##########
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
spec:
  redirectScheme:
    scheme: https
    permanent: true

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: custom-headers-request
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
      
---
###### Middleware Chain ################
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-to-https
spec:
  chain:
    middlewares:
      - name: redirect-https
      - name: cf-ipwhitelist