# ingressRoute:
#   dashboard:
#     # -- Create an IngressRoute for the dashboard
#     enabled: true
#     middlewares:
#       - name: basic-auth

additionalArguments:
  - --certificatesresolvers.le.acme.keyType=RSA2048
  - --serversTransport.insecureSkipVerify=true

env:
  - name: CF_DNS_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cf-creds
        key: dnsapitoken

tlsOptions:
  default:
    minVersion: VersionTLS12
    cipherSuites:
      # Recommended ciphers for TLSv1.2
      - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
      - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
      - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
      # Recommended ciphers for TLSv1.3
      - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
      - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
      - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305

service:
  enabled: true
  single: false
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/exoscale-loadbalancer-external: "false"
    service.beta.kubernetes.io/exoscale-loadbalancer-service-strategy: "round-robin"
    external-dns.alpha.kubernetes.io/hostname: traefik.mervinhemaraju.com
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    external-dns.alpha.kubernetes.io/cloudflare-record-comment: "Managed by ExternalDNS"

persistence:
  enabled: true
  name: data
  accessMode: ReadWriteOnce
  size: 1Gi
  path: /data
  storageClass: "oci-bv"
  annotations: {}


certificatesResolvers:
  le:
    acme:
      email: mervinhemaraju16@gmail.com
      dnsChallenge:
      # also add the provider's required configuration under env
      # or expand then from secrets/configmaps with envfrom
      # cf. https://doc.traefik.io/traefik/https/acme/#providers
        provider: cloudflare
      # add futher options for the dns challenge as needed
      # cf. https://doc.traefik.io/traefik/https/acme/#dnschallenge
        resolvers:
          - 1.1.1.1
          - 8.8.8.8
        delayBeforeCheck: 60
      storage: /data/acme.json

resources:
  requests:
    cpu: "200m"
    memory: "300Mi"
  limits:
    cpu: "300m"
    memory: "512Mi"

podSecurityContext:
  fsGroupChangePolicy: "OnRootMismatch"
  runAsGroup: 65532
  runAsNonRoot: true
  runAsUser: 65532
  fsGroup: 65532

# ports:
#   web:
#     proxyProtocol:
#       trustedIPs:
#         - 127.0.0.1/32
#         - 10.0.0.0/8
#         - 173.245.48.0/20
#         - 103.21.244.0/22
#         - 103.22.200.0/22
#         - 103.31.4.0/22
#         - 141.101.64.0/18
#         - 108.162.192.0/18
#         - 190.93.240.0/20
#         - 188.114.96.0/20
#         - 197.234.240.0/22
#         - 198.41.128.0/17
#         - 162.158.0.0/15
#         - 104.16.0.0/13
#         - 104.24.0.0/14
#         - 172.64.0.0/13
#         - 131.0.72.0/22
#     forwardedHeaders:
#       trustedIPs:
#         - 127.0.0.1/32
#         - 10.0.0.0/8
#         - 173.245.48.0/20
#         - 103.21.244.0/22
#         - 103.22.200.0/22
#         - 103.31.4.0/22
#         - 141.101.64.0/18
#         - 108.162.192.0/18
#         - 190.93.240.0/20
#         - 188.114.96.0/20
#         - 197.234.240.0/22
#         - 198.41.128.0/17
#         - 162.158.0.0/15
#         - 104.16.0.0/13
#         - 104.24.0.0/14
#         - 172.64.0.0/13
#         - 131.0.72.0/22
#   websecure:
#     tls:
#       certResolver: "le"
#     proxyProtocol:
#       trustedIPs:
#         - 127.0.0.1/32
#         - 10.0.0.0/8
#         - 173.245.48.0/20
#         - 103.21.244.0/22
#         - 103.22.200.0/22
#         - 103.31.4.0/22
#         - 141.101.64.0/18
#         - 108.162.192.0/18
#         - 190.93.240.0/20
#         - 188.114.96.0/20
#         - 197.234.240.0/22
#         - 198.41.128.0/17
#         - 162.158.0.0/15
#         - 104.16.0.0/13
#         - 104.24.0.0/14
#         - 172.64.0.0/13
#         - 131.0.72.0/22
#     forwardedHeaders:
#       trustedIPs:
#         - 127.0.0.1/32
#         - 10.0.0.0/8
#         - 173.245.48.0/20
#         - 103.21.244.0/22
#         - 103.22.200.0/22
#         - 103.31.4.0/22
#         - 141.101.64.0/18
#         - 108.162.192.0/18
#         - 190.93.240.0/20
#         - 188.114.96.0/20
#         - 197.234.240.0/22
#         - 198.41.128.0/17
#         - 162.158.0.0/15
#         - 104.16.0.0/13
#         - 104.24.0.0/14
#         - 172.64.0.0/13
#         - 131.0.72.0/22