deployment:
  replicas: 2

service:
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "10"
    service.beta.kubernetes.io/oci-load-balancer-security-list-management-mode: "None"

ports:
  web:
    port: 8080      # Non-privileged port internally
    expose: true
    exposedPort: 80 # External port 80
    protocol: TCP
  websecure:
    port: 8443      # Non-privileged port internally
    expose: true 
    exposedPort: 443 # External port 443
    protocol: TCP
  traefik:
    port: 9000
    expose: false
    protocol: TCP

api:
  dashboard: true
  insecure: true

providers:
  kubernetesIngress:
    enabled: true
  kubernetesCRD:
    enabled: true

entryPoints:
  web:
    address: ":8080"    # Match the internal port
  websecure:
    address: ":8443"    # Match the internal port