apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptimekuma
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  destination:
    server: https://kubernetes.default.svc
    namespace: uptimekuma
  
  source:
    path: helm/src/uptimekuma
    repoURL: https://github.com/mervinhemaraju/k8-poseidon
    targetRevision: main
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
  
  # Ignore fields that ExternalSecrets Operator adds at runtime
  ignoreDifferences:
    - group: external-secrets.io
      kind: ExternalSecret
      jsonPointers:
        - /spec/data/0/conversionStrategy
        - /spec/data/0/decodingStrategy
        - /spec/data/0/metadataPolicy