apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  accounts.th3pl4gu3: apiKey, login
  kustomize.buildOptions: --enable-helm
  url: "https://argocd.plagueworks.org"
  server.disable.auth: "false"
  resource.exclusions: |
      - apiGroups:
          - "*"
        kinds:
          - VolumeSnapshot
          - Backup
        clusters:
          - '*'
  dex.config: |


    connectors:

      # --- Connector 1: Auth0 OIDC ---
      - type: oidc
        id: auth0
        name: Auth0
        config:
          issuer: $dex.auth0.domain
          clientID: $dex.auth0.clientId
          clientSecret: $dex.auth0.clientSecret
          requestedScopes:
            - openid
            - profile
            - email

      # --- Connector 2: Azure Apollo AD ---
      - type: microsoft
        id: azure
        name: AzureAD
        config:
          clientID: $dex.azure.clientId
          clientSecret: $dex.azure.clientSecret
          tenant: $dex.azure.tenantId

          scopes:
            - openid
            - profile
            - email