apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: github-arc

helmCharts:
  - name: gha-runner-scale-set-controller
    repo: oci://ghcr.io/actions/actions-runner-controller-charts
    version: 0.9.3
    releaseName: arc-controller
    namespace: github-arc
    includeCRDs: true