name: Deploy Applications to K8 Cluster

on:
  push:
    branches:
      - main
      - dev
      - staging
      - feature/*
      - fix/*
      - hotfix/*
      - release/*
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  KFILTVERSION: "0.0.8"
  OCI_POSEIDON_REGION: "uk-london-1"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Authenticate to Doppler Secrets"
        uses: dopplerhq/secrets-fetch-action@v1.3.0
        id: doppler
        with:
          doppler-token: ${{ secrets.DOPPLER_TOKEN }}
          doppler-project: cloud-iac-main
          doppler-config: prd

      - name: "Setup OCI Config File"
        run: |

          # Create the oci directory if it doesn't exist
          mkdir -p ~/.oci

          # Create local variable for private key path
          KEY_PATH=~/.oci/oci_api_key.pem 

          # Create the oci_api_key.pem file
          echo "${{ steps.doppler.outputs.OCI_POSEIDON_PRIVATE_KEY }}" > $KEY_PATH
          chmod 600 ~/.oci/oci_api_key.pem

          # Create the config file
          echo "[DEFAULT]" > ~/.oci/config
          echo "user=${{ steps.doppler.outputs.OCI_POSEIDON_USER_OCID }}" >> ~/.oci/config
          echo "fingerprint=${{ steps.doppler.outputs.OCI_POSEIDON_FINGERPRINT }}" >> ~/.oci/config
          echo "key_file=$KEY_PATH" >> ~/.oci/config
          echo "tenancy=${{ steps.doppler.outputs.OCI_POSEIDON_TENANCY_OCID }}" >> ~/.oci/config
          echo "region=${{ env.OCI_POSEIDON_REGION }}" >> ~/.oci/config

      - name: Install OCI CLI
        run: |
          curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh > install.sh
          chmod +x install.sh
          ./install.sh --accept-all-defaults
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: RUN OCI CLI
        run: |
          oci iam compartment list --compartment-id-in-subtree=true

      #   - name: Retrieve the OCID of a named compartment in tenancy
      #     uses: oracle-actions/run-oci-cli-command@v1.3.2
      #     id: find-compartment-id
      #     with:
      #       command: "iam compartment list --compartment-id-in-subtree=true"

      - name: Install Kfilt
        run: |
          wget -O /usr/local/bin/kfilt https://github.com/ryane/kfilt/releases/download/v${KFILTVERSION}/kfilt_${KFILTVERSION}_linux_amd64
          chmod +x /usr/local/bin/kfilt
