name: Deploy Applications to K8 Cluster

on:
  push:
    branches:
      - main
      - dev
      - staging
      - feature/*
      - fix/*
      - hotfix/*
      - release/*
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  KFILTVERSION: "0.0.8"
  OCI_POSEIDON_REGION: "uk-london-1"
  OCI_CLUSTER_NAME: "applications"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Authenticate to Doppler Secrets"
        uses: dopplerhq/secrets-fetch-action@v1.3.0
        id: doppler
        with:
          doppler-token: ${{ secrets.DOPPLER_TOKEN }}
          doppler-project: cloud-iac-main
          doppler-config: prd

      - name: "Setup OCI Config File"
        run: |

          # Create the oci directory if it doesn't exist
          mkdir -p ~/.oci

          # Create local variable for private key path
          KEY_PATH=~/.oci/oci_api_key.pem 

          # Append OCI_API_KEY to the key file
          echo "OCI_API_KEY" >> $KEY_PATH   

          # Create the oci_api_key.pem file
          echo "${{ steps.doppler.outputs.OCI_POSEIDON_PRIVATE_KEY }}" > $KEY_PATH
          chmod 600 ~/.oci/oci_api_key.pem

          # Create the config file
          echo "[DEFAULT]" > ~/.oci/config
          echo "user=${{ steps.doppler.outputs.OCI_POSEIDON_USER_OCID }}" >> ~/.oci/config
          echo "fingerprint=${{ steps.doppler.outputs.OCI_POSEIDON_FINGERPRINT }}" >> ~/.oci/config
          echo "key_file=$KEY_PATH" >> ~/.oci/config
          echo "tenancy=${{ steps.doppler.outputs.OCI_POSEIDON_TENANCY_OCID }}" >> ~/.oci/config
          echo "region=${{ env.OCI_POSEIDON_REGION }}" >> ~/.oci/config

      - name: Install OCI CLI
        run: |
          echo "Downloading and installing OCI CLI..."   
          curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh > install.sh
          chmod +x install.sh

          echo "Installing OCI CLI..."
          ./install.sh --accept-all-defaults
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Find The OKE Cluster ${{ env.OCI_CLUSTER_NAME }}
        id: find-cluster-id
        run: |
          echo "Searching for OKE cluster named '${{ env.OCI_CLUSTER_NAME }}'..."

          CLUSTER_ID=$(oci ce cluster list \
            --compartment-id $COMPARTMENT_ID \
            --lifecycle-state ACTIVE \
            --all \
            --query "data[?name=='${{ env.OCI_CLUSTER_NAME }}'].id | [0]" \
            --raw-output)

          if [ -z "$CLUSTER_ID" ] || [ "$CLUSTER_ID" == "null" ]; then
            echo "Error: No OKE cluster named '${{ env.OCI_CLUSTER_NAME }}' found in compartment $COMPARTMENT_ID"
            exit 1
          fi

          echo "Found OKE cluster '${{ env.OCI_CLUSTER_NAME }}' with ID: $CLUSTER_ID"

          # Set as step output
          echo "cluster_id=$CLUSTER_ID" >> $GITHUB_OUTPUT

          # Mask it as well
          echo "::add-mask::$CLUSTER_ID"

      - name: Generate OKE Kubeconfig
        run: |
          echo "Generating kubeconfig for cluster..."

          oci ce cluster create-kubeconfig \
            --cluster-id ${{ steps.find-cluster-id.outputs.cluster_id }} \
            --file $HOME/.kube/config \
            --region ${{ env.OCI_POSEIDON_REGION }} \
            --token-version 2.0.0 \
            --kube-endpoint PUBLIC_ENDPOINT

          echo "✓ Kubeconfig generated successfully"

      - name: Install Kfilt
        run: |
          wget -O /usr/local/bin/kfilt https://github.com/ryane/kfilt/releases/download/v${KFILTVERSION}/kfilt_${KFILTVERSION}_linux_amd64
          chmod +x /usr/local/bin/kfilt
