apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  accounts.th3pl4gu3: apiKey, login
  kustomize.buildOptions: --enable-helm
  resource.exclusions: |
      - apiGroups:
          - "*"
        kinds:
          - VolumeSnapshot
          - Backup
        clusters:
          - '*'

