apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  accounts.th3pl4gu3: apiKey, login
  kustomize.buildOptions: --enable-helm
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
data:
  policy.default: role:readonly
  policy.csv: |
    g, th3pl4gu3, role:admin