apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  accounts.mervinhemaraju: apiKey, login
  kustomize.buildOptions: --enable-helm
  resource.exclusions: |
      - apiGroups:
          - "*"
        kinds:
          - VolumeSnapshot
          - Backup
        clusters:
          - '*'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
data:
  policy.default: role:readonly
  policy.csv: |
    p, mervinhemaraju, applications, get, */*, allow
    p, mervinhemaraju, applications, override, */*, allow
    p, mervinhemaraju, applications, sync, */*, allow
    p, mervinhemaraju, applications, update, */*, allow
    p, mervinhemaraju, logs, get, */*, allow
    p, mervinhemaraju, exec, create, */*, allow
    p, mervinhemaraju, projects, get, *, allow
