apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: argocd
  annotations:
    external-dns.alpha.kubernetes.io/target: traefik.mervinhemaraju.com
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`argo.mervinhemaraju.com`)
      services:
        - name: argocd-server
          port: 80 
    - kind: Rule
      match: Host(`argo.mervinhemaraju.com`) && Header(`Content-Type`, `application/grpc`)
      priority: 11
      services:
        - name: argocd-server
          port: 80
          scheme: h2c
  tls:
    certResolver: le