apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: argocd

namespace: argocd

resources:
  - es.yaml 
  - ingress.yaml
  - project.yaml
  - default-application.yaml
  # - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/v3.1.9/manifests/install.yaml

patches:
  - path: ./patches/cm.yaml
  - path: ./patches/rbac-cm.yaml

configMapGenerator:
  - name: argocd-cmd-params-cm
    behavior: merge
    literals:
      - server.insecure="true"