apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: argocd

namespace: argocd

resources:
  - namespace.yaml
  - ingress.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml