apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  namespace: argocd
data:
  # Disable internal TLS since Traefik handles it
  server.insecure: "true"
  server.basehref: "/argocd"