apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default-apps
  namespace: argocd
spec:
  description: Simple project with full access for all applications
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'